Repository hicommonwealth/edgeware-node, pull requests merged in 2020-02, with the labels that each got.

#127 Add some documentation for contribution and style
  .github/PULL_REQUEST_TEMPLATE.md
  docs/CODE_OF_CONDUCT.adoc
  docs/CONTRIBUTING.adoc
Labels: A0-pleasereview

#140 node: disable GRANDPA observer
  node/cli/src/service.rs
Labels: A0-pleasereview, A8-looksgood

#141 runtime: disable GRANDPA finality fallback
  node/runtime/src/lib.rs
Labels: A8-looksgood
